### ISSUE TITLE
Is this still being maintained?

### ISSUE THREAD

**Issue by guyisra** [tcocca/acts_as_follower#54]
Sorry to post such an issue again, but it seems that over a year with no updates..

@tcocca maybe its best to add more maintainers, since this gem has valuable functionality that everyone gain by cooperating than using in-house, closed source solutions

**Comment by jcoyne** [comment]
@tcocca Please transfer this gem to someone who wants to maintain it. You're doing a disservice to the ruby community by letting it whither on the vine.

**Comment by tcocca** [comment]
@guyisra @jcoyne happy to add maintainers if anybody is willing to come onboard.

~ Tom

**Comment by jcoyne** [comment]
I'd be willing to take it on.

**Comment by tcocca** [comment]
@jcoyne Sent you an invite.  We can chat about the plans.

**Comment by jcoyne** [comment]
@tcocca Okay. I'd like to merge in the PR for Rails 5 and then cut a release.  Any problems with that?

**Comment by tcocca** [comment]
@jcoyne which PR?  Is it going to break rails 4 compatibility?  I'm not against cutting a new version, just want to make sure we get a new version number and get it documented which version to use.

Am I going to have to give you access on rubygems as well to cut a new version?

**Comment by jcoyne** [comment]
There should be no problem preserving rails 4 & 5 compatibility.  Yes, I will need rubygems access in order to push new revisions.
