### ISSUE TITLE
Rails 5 followable_type

### ISSUE THREAD

**Issue by jimboqu** [tcocca/acts_as_follower#77]
Hi there

Firstly, just to say thanks for putting this gem together and taking the time to look at this. 

I'm building something in Rails 5 and have come up against a slight problem. When selecting objects a user is following, the follower_type is coming up "user" but followable_type is coming up as "ApplicationRecord". I guess acts_as_followable is not working in the model.

Is there a quick fix for this? 

Thanks again

Jimboqu

**Comment by jcoyne** [comment]
Can you retry with the latest version from the master branch? I think this fixes it.

**Comment by jimboqu** [comment]
Awesome, that did the trick. Many thanks for looking at it so quickly.

**Comment by jimboqu** [comment]
I think I spoke too soon. It seems to be a little temperamental. Sometimes it works, then it suddenly goes back to adding "ApplictionRecord" as Followable_type again.  

Just so you know I added the initializers file with: 

`ActsAsFollower.custom_parent_classes = [CustomRecord]`

Cheers

Jimboqu

**Comment by ashchan** [comment]
I still see this problem in my projects. `User` inherits from `ApplicationRecord` (when it inherits from `ActiveRecord::Base` it just works fine.

`ActiveAsFollowers::FollowerLib`'s `parent_classes` returns `[ApplicationRecord(abstract), ActiveRecord::Base]`, and when check if `User.superclass` is within this array it return false!

While I don't know what's the problem with `ApplicationRecord(abstract)` and `ApplicationRecord`, adding `ApplicationRecord` explicitly in initializer does solve the problem:

`ActsAsFollower.custom_parent_classes = [ ApplicationRecord ]`.

**Comment by JWesorick** [comment]
Is there a new release with this fix or do I have to use the master branch?
