### ISSUE TITLE
acts_as_follower gem is not working in rails5

### ISSUE THREAD

**Issue by jigarbhatt2711** [tcocca/acts_as_follower#79]
acts_as_follower gem working fine in Rails4 but it is not working Rails5.

When i integrate and try to use follow function in console i got following error.

 user = User.find(1)
 user2 = User.find(2)
user.follow(user2)

If you are using sqlite3 database,i got following error.
**no table found error will be display**

If you are using pg database,i got following error.
**TypeError: no implicit conversion of nil into String**

**Comment by tcocca** [comment]
@jigarbhatt2711 Could you please include full backtraces for these errors?

**Comment by mozillo** [comment]
Follow Load (0.2ms)  SELECT  "follows".* FROM "follows" WHERE "follows"."follower_id" = ? AND "follows"."follower_type" = ? AND "follows"."followable_id" = ? AND "follows"."followable_type" = ? LIMIT ?  [["follower_id", 1], ["follower_type", "User"], ["followable_id", 2], ["followable_type", "ApplicationRecord"], ["LIMIT", 1]]
   (0.1ms)  begin transaction
   (0.1ms)  rollback transaction
Completed 500 Internal Server Error in 209ms (ActiveRecord: 4.6ms)



ActiveRecord::StatementInvalid (Could not find table ''):

app/controllers/sharing_controller.rb:37:in `post_friends_join'
app/controllers/sharing_controller.rb:7:in `index'

**Comment by jigarbhatt2711** [comment]
@tcocca  i am in truble. this gem gives exception in rails 5.

Will you please help me to resolve it otherwise i will have to do it mannualy.

I am going to explain to you steps what i followed

1) rails new demo_follow
2)create user scaffold and install gem and follow all the steps
3)when i open console

 tried to use follow function in console i got following error.

user = User.find(1)
user2 = User.find(2)
user.follow(user2)

**i got following error.
no table found error will be display**

i can share this demo with you if you want

**Comment by merqlove** [comment]
Did you done `db:create db:migrate` process? (supposed, that you have AAF migrations inside your db/migrations folder).
I'm integrated it with rails 5 project, and it works fine.

**Comment by jigarbhatt2711** [comment]
@merqlove  Thanks for reply

I tried it again now it gives error 

**NoMethodError: undefined method `follow'** 

do we need to anything in  **config/initializers/acts_as_follower.rb** ?

please guide me I am stuck here

**Comment by merqlove** [comment]
Jigar, your rails v 5.0.0.1?
You did this?:
rails generate acts_as_follower
rails db:migrate
You added to your models:  acts_as_follower acts_as_followable ?

Best regards, 
Alexander Merkulov

**Comment by jigarbhatt2711** [comment]
my rails version is rails (5.0.0.1)

i did this 2 things
rails generate acts_as_follower
rails db:migrate

then i generate user scaffold and added 
acts_as_followable
acts_as_follower

then rake db:migrate

**Console**

user = User.find(1)
user2 = User.find(2)
user.follow(user2)

i got following error.
no table found error will be display

**Comment by merqlove** [comment]
Which table? Orm Postgres?

Best regards, 
Alexander Merkulov

**Comment by jigarbhatt2711** [comment]
sqlite3 database

then not showing us any table name.
![error](https://cloud.githubusercontent.com/assets/5001934/18812039/a9956552-82e4-11e6-97b9-bd65e2a484e8.png)

**Comment by jigarbhatt2711** [comment]
this is my demo project. You can clone and check.

https://github.com/jigarbhatt2711/act_as_follow_demo

thank you

**Comment by merqlove** [comment]
I think here can be something with SQLite adapter or migration
Check if table exists.

Best regards, 
Alexander Merkulov

**Comment by jigarbhatt2711** [comment]
yes tables are exist

this is my schema file

create_table "follows", force: :cascade do |t|
    t.string   "followable_type",                 null: false
    t.integer  "followable_id",                   null: false
    t.string   "follower_type",                   null: false
    t.integer  "follower_id",                     null: false
    t.boolean  "blocked",         default: false, null: false
    t.datetime "created_at"
    t.datetime "updated_at"
    t.index ["followable_id", "followable_type"], name: "fk_followables"
    t.index ["follower_id", "follower_type"], name: "fk_follows"
  end

  create_table "users", force: :cascade do |t|
    t.string   "name"
    t.integer  "age"
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
  end

**Comment by jigarbhatt2711** [comment]
it's not error about only sqlite3

when i use postgresql database at that time i got following error

**TypeError: no implicit conversion of nil into String**

there must be something missing by act_as_follower gem in rails5

**Comment by merqlove** [comment]
Ok, I will  try to run it at Sunday
But after first look to the code I can say:
Try to remove from follow model:
self.table_name = 'follows'

And try to inherit it from ApplicationRecord

Best regards, 
Alexander Merkulov

**Comment by jigarbhatt2711** [comment]
i changed this 2 things but still not working.

thanks for your given valuable time.please message me if you will find any solution.

Thank You

**Comment by merqlove** [comment]
Try to change 

gem "acts_as_follower"

To

gem "acts_as_follower", github: "tcocca/acts_as_follower"

You have old gem in deps 

Best regards, 
Alexander Merkulov

**Comment by jigarbhatt2711** [comment]
Many Many thanks @merqlove 

Now It is working.

Thanks a lot my friend

**Comment by merqlove** [comment]
@tcocca, I think README must have instruction for rails5:

gem "acts_as_follower", github: "tcocca/acts_as_follower"

Or release new version

Best regards, 
Alexander Merkulov

**Comment by jigarbhatt2711** [comment]
@merqlove  I totally agree with you

**Comment by ephracis** [comment]
I would really prefer a new release. 😄
